# Generated by Django 5.2.6 on 2025-09-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FalhaDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falha_ocorrida', models.CharField(max_length=500, verbose_name='Falha Ocorrida')),
                ('data_falha', models.DateField(verbose_name='Data da Falha')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falhas', to='api.unidadedjango', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Falha',
                'verbose_name_plural': 'Falhas',
                'ordering': ['-data_falha', '-created_at'],
            },
        ),
    ]
