# Generated by Django 5.2.6 on 2025-09-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_falhadjango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadedjango',
            name='tecnico_unidade',
            field=models.CharField(blank=True, max_length=200, verbose_name='Técnico da Unidade'),
        ),
    ]
